### ISSUE TITLE
Please help, how can I download this file?

### ISSUE THREAD

**Issue by Karel-Wala** [lcorbasson/sh3d-importedfurniture#1]
https://github.com/lcorbasson/sh3d-importedfurniture/blob/c7e9cbcfddc07dd296b15a2fb8b1e80594e82233/Libraries/ODG8-Pro/ODG8-Pro_Library.sh3f#L3

**Comment by Karel-Wala** [comment]
@lcorbasson Can you help me please?

**Comment by lcorbasson** [comment]
Hi @Karel-Wala, you'll have to git-clone the repository, GitHub doesn't allow you to download it directly from the Web. See the home page for instructions.
